hnc_project_homepage:
    path:     /
    defaults: { _controller: HncProjectBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: HncProjectBundle:User:register }

login:
    path:     /login
    defaults: { _controller: HncProjectBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: HncProjectBundle:User:logout }

user_settings:
    path:     /my_account
    defaults: { _controller: HncProjectBundle:User:user_settings }
